name: CI Pipeline
on:
  push:
  pull_request:
    branches:
      - develop
      - feature/*
jobs:
  lint:
    name: Check the linting and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  typecheck:
    name: Run the TS type-checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Type check
        run: yarn typecheck
  # test:
  #   name: Run the Vitest+RTL unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Configure Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22.12.0
  #     - name: Install Yarn dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Unit Test
  #       run: yarn test
  build:
    name: Build the React application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
